version: 2.1

aliases:
  - &cache-key cache-{{ checksum "yarn.lock" }}

executors:
  default:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache-key
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          key: *cache-key
          paths: 
            - node_modules
            - .yarn/install-state.gz

  lint:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache-key
      - run:
          name: Lint files
          command: yarn lint

  typescript:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache-key
      - run:
          name: Typecheck files
          command: yarn typescript

  build-and-publish:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache-key
      - run:
          name: Build and publish
          command: yarn prepare && yarn npm publish

workflows:
  build-and-test:
    jobs:
      - install-dependencies:
          context:
            - STAGING
      - lint:
          requires:
            - install-dependencies
          context:
            - STAGING
      - typescript:
          requires:
            - install-dependencies
          context:
            - STAGING
      - build-and-publish:
          requires:
            - lint
            - typescript
          context:
            - github-publish-context
            - STAGING
          filters:
            branches:
              only:
                - master
